name: "Test packer install"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Test odin install"
        run: devcontainer features test --skip-scenarios -f packer -i ubuntu .